name: room_manager
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  syncfusion_flutter_calendar: ^26.1.40+1
  syncfusion_localizations: ^26.1.40
  flutter_localization: ^0.2.0
  google_fonts: ^6.2.1
  elegant_notification: ^2.2.1
  flutter_login: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Screenshot 2024-06-18 163920.png
    - assets/images/logo.png
